package albumirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.30 11:23:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlbumiTest {



  // Generated by ComTest BEGIN
  /** testGetNimi30 */
  @Test
  public void testGetNimi30() {    // Albumi: 30
    Albumi levy1 = new Albumi(); 
    levy1.vastaaAlbumi(); 
    { String _l_=levy1.getNimi(),_r_="Jytäkesä .*"; if ( !_l_.matches(_r_) ) fail("From: Albumi line: 33" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta93 */
  @Test
  public void testAseta93() {    // Albumi: 93
    Albumi albumi = new Albumi(); 
    assertEquals("From: Albumi line: 95", null, albumi.aseta(1, "Jytää")); 
    assertEquals("From: Albumi line: 96", "Julkaisuvuosi väärin jono = \"Jytää\"", albumi.aseta(3, "Jytää")); 
    assertEquals("From: Albumi line: 97", null, albumi.aseta(3, "1990")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi197 */
  @Test
  public void testRekisteroi197() {    // Albumi: 197
    Albumi levy1 = new Albumi(); 
    assertEquals("From: Albumi line: 199", 0, levy1.getTunnusNro()); 
    levy1.rekisteroi(); 
    Albumi levy2 = new Albumi(); 
    levy2.rekisteroi(); 
    int n1 = levy1.getTunnusNro(); 
    int n2 = levy2.getTunnusNro(); 
    assertEquals("From: Albumi line: 205", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString240 */
  @Test
  public void testToString240() {    // Albumi: 240
    Albumi albumi = new Albumi(); 
    albumi.parse("     5    | JYTÄÄ   | Matti ja Mara-katti"); 
    assertEquals("From: Albumi line: 243", true, albumi.toString().startsWith("5|JYTÄÄ|Matti ja Mara-katti|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse263 */
  @Test
  public void testParse263() {    // Albumi: 263
    Albumi albumi = new Albumi(); 
    albumi.parse("     5    | JYTÄÄ   | Matti ja Mara-katti"); 
    assertEquals("From: Albumi line: 266", true, albumi.toString().startsWith("5|JYTÄÄ|Matti ja Mara-katti|")); 
    albumi.rekisteroi(); 
    int j = albumi.getTunnusNro(); 
    albumi.parse(""+(j+10)); 
    albumi.rekisteroi(); 
    assertEquals("From: Albumi line: 271", j+10+1, albumi.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone328 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone328() throws CloneNotSupportedException {    // Albumi: 328
    Albumi albumi = new Albumi(); 
    albumi.parse("1|Heviä|Musta sapatti"); 
    Albumi kopio = albumi.clone(); 
    assertEquals("From: Albumi line: 333", albumi.toString(), kopio.toString()); 
    albumi.parse("3|Rokkia|Kirka"); 
    assertEquals("From: Albumi line: 335", false, kopio.toString().equals(albumi.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals351 */
  @Test
  public void testEquals351() {    // Albumi: 351
    Albumi albumi1 = new Albumi(); 
    albumi1.parse("3|Rokkia|Kirka"); 
    Albumi albumi2 = new Albumi(); 
    albumi2.parse("3|Rokkia|Kirka"); 
    Albumi albumi3 = new Albumi(); 
    albumi3.parse("3|Rokkia|Kirko"); 
    assertEquals("From: Albumi line: 358", true, albumi1.equals(albumi2)); 
    assertEquals("From: Albumi line: 359", false, albumi2.equals(albumi3)); 
    assertEquals("From: Albumi line: 360", true, albumi2.equals(albumi1)); 
  } // Generated by ComTest END
}