package albumirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.26 11:59:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlbumiTest {



  // Generated by ComTest BEGIN
  /** testGetNimi27 */
  @Test
  public void testGetNimi27() {    // Albumi: 27
    Albumi levy1 = new Albumi(); 
    levy1.vastaaAlbumi(); 
    { String _l_=levy1.getNimi(),_r_="Jytäkesä .*"; if ( !_l_.matches(_r_) ) fail("From: Albumi line: 30" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi73 */
  @Test
  public void testRekisteroi73() {    // Albumi: 73
    Albumi levy1 = new Albumi(); 
    assertEquals("From: Albumi line: 75", 0, levy1.getTunnusNro()); 
    levy1.rekisteroi(); 
    Albumi levy2 = new Albumi(); 
    levy2.rekisteroi(); 
    int n1 = levy1.getTunnusNro(); 
    int n2 = levy2.getTunnusNro(); 
    assertEquals("From: Albumi line: 81", n2-1, n1); 
  } // Generated by ComTest END
}