package albumirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.26 11:59:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlbumitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa30 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa30() throws SailoException {    // Albumit: 30
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(); 
    assertEquals("From: Albumit line: 34", 0, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 35", 1, albumit.getLkm()); 
    albumit.lisaa(levy2); assertEquals("From: Albumit line: 36", 2, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 37", 3, albumit.getLkm()); 
    assertEquals("From: Albumit line: 38", levy1, albumit.anna(0)); 
    assertEquals("From: Albumit line: 39", levy2, albumit.anna(1)); 
    assertEquals("From: Albumit line: 40", levy1, albumit.anna(2)); 
    assertEquals("From: Albumit line: 41", false, albumit.anna(1) == levy1); 
    assertEquals("From: Albumit line: 42", true, albumit.anna(1) == levy2); 
    try {
    assertEquals("From: Albumit line: 43", levy1, albumit.anna(3)); 
    fail("Albumit: 43 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 44", 4, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 45", 5, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 46", 6, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 47", 7, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 48", 8, albumit.getLkm()); 
    try {
    albumit.lisaa(levy1); 
    fail("Albumit: 49 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}