package albumirekisteri.test;
// Generated by ComTest BEGIN
import albumirekisteri.*;
import java.io.File;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.30 11:54:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlbumitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa45 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa45() throws SailoException {    // Albumit: 45
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(); 
    assertEquals("From: Albumit line: 49", 0, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 50", 1, albumit.getLkm()); 
    albumit.lisaa(levy2); assertEquals("From: Albumit line: 51", 2, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 52", 3, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 53", 4, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 54", 5, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 55", 6, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 56", 7, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 57", 8, albumit.getLkm()); 
    Iterator<Albumi> alb = albumit.iterator(); 
    assertEquals("From: Albumit line: 59", levy1, alb.next()); 
    assertEquals("From: Albumit line: 60", levy2, alb.next()); 
    assertEquals("From: Albumit line: 61", levy1, alb.next()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 62", 9, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 63", 10, albumit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa86 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaa86() throws SailoException,CloneNotSupportedException {    // Albumit: 86
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(); 
    levy1.rekisteroi(); 
    levy2.rekisteroi(); 
    assertEquals("From: Albumit line: 93", 0, albumit.getLkm()); 
    albumit.korvaaTaiLisaa(levy1); 
    assertEquals("From: Albumit line: 95", 1, albumit.getLkm()); 
    albumit.korvaaTaiLisaa(levy2); 
    assertEquals("From: Albumit line: 97", 2, albumit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista238 
   * @throws SailoException when error
   */
  @Test
  public void testPoista238() throws SailoException {    // Albumit: 238
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(), levy3 = new Albumi(); 
    levy1.rekisteroi(); levy2.rekisteroi(); levy3.rekisteroi(); 
    int id1 = levy1.getTunnusNro(); 
    albumit.lisaa(levy1); albumit.lisaa(levy2); albumit.lisaa(levy3); 
    assertEquals("From: Albumit line: 245", 1, albumit.poista(id1+1)); 
    assertEquals("From: Albumit line: 246", null, albumit.annaId(id1+1)); assertEquals("From: Albumit line: 246", 2, albumit.getLkm()); 
    assertEquals("From: Albumit line: 247", 1, albumit.poista(id1)); assertEquals("From: Albumit line: 247", 1, albumit.getLkm()); 
    assertEquals("From: Albumit line: 248", 0, albumit.poista(id1+3)); assertEquals("From: Albumit line: 248", 1, albumit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAlbumitIterator276 
   * @throws SailoException when error
   */
  @Test
  public void testAlbumitIterator276() throws SailoException {    // Albumit: 276
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(); 
    assertEquals("From: Albumit line: 282", 0, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 283", 1, albumit.getLkm()); 
    albumit.lisaa(levy2); assertEquals("From: Albumit line: 284", 2, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 285", 3, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 286", 4, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 287", 5, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 288", 6, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 289", 7, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 290", 8, albumit.getLkm()); 
    Iterator<Albumi> alb = albumit.iterator(); 
    assertEquals("From: Albumit line: 292", levy1, alb.next()); 
    assertEquals("From: Albumit line: 293", levy2, alb.next()); 
    assertEquals("From: Albumit line: 294", levy1, alb.next()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 295", 9, albumit.getLkm()); 
    albumit.lisaa(levy1); assertEquals("From: Albumit line: 296", 10, albumit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi334 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi334() throws SailoException {    // Albumit: 334
    Albumit albumit = new Albumit(); 
    Albumi albumi1 = new Albumi(); 
    albumi1.parse("1|Rokkia|Kirka"); 
    Albumi albumi2 = new Albumi(); 
    albumi2.parse("2|Jytää|Jukka"); 
    Albumi albumi3 = new Albumi(); 
    albumi3.parse("3|Folkia|Pekka"); 
    albumit.lisaa(albumi1); 
    albumit.lisaa(albumi2); 
    albumit.lisaa(albumi3); 
    List<Albumi> loytyneet; 
    loytyneet = (List<Albumi>)albumit.etsi("*j*",1); 
    assertEquals("From: Albumit line: 348", 1, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId368 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId368() throws SailoException {    // Albumit: 368
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(), levy3 = new Albumi(); 
    levy1.rekisteroi(); 
    levy2.rekisteroi(); 
    levy3.rekisteroi(); 
    int id1 = levy1.getTunnusNro(); 
    albumit.lisaa(levy1); 
    albumit.lisaa(levy2); 
    albumit.lisaa(levy3); 
    assertEquals("From: Albumit line: 379", true, albumit.annaId(id1) == levy1); 
    assertEquals("From: Albumit line: 380", true, albumit.annaId(id1+1) == levy2); 
    assertEquals("From: Albumit line: 381", true, albumit.annaId(id1+2) == levy3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId396 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId396() throws SailoException {    // Albumit: 396
    Albumit albumit = new Albumit(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(), levy3 = new Albumi(); 
    levy1.rekisteroi(); 
    levy2.rekisteroi(); 
    levy3.rekisteroi(); 
    int id1 = levy1.getTunnusNro(); 
    albumit.lisaa(levy1); 
    albumit.lisaa(levy2); 
    albumit.lisaa(levy3); 
    assertEquals("From: Albumit line: 407", 1, albumit.etsiId(id1+1)); 
    assertEquals("From: Albumit line: 408", 2, albumit.etsiId(id1+2)); 
  } // Generated by ComTest END
}