package albumirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.30 12:14:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi76 */
  @Test
  public void testRekisteroi76() {    // Kappale: 76
    Kappale laulu1 = new Kappale(); 
    assertEquals("From: Kappale line: 78", 0, laulu1.getTunnusNro()); 
    laulu1.rekisteroi(); 
    Kappale laulu2 = new Kappale(); 
    laulu2.rekisteroi(); 
    int n1 = laulu1.getTunnusNro(); 
    int n2 = laulu2.getTunnusNro(); 
    assertEquals("From: Kappale line: 84", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse132 */
  @Test
  public void testParse132() {    // Kappale: 132
    Kappale kap = new Kappale(); 
    kap.parse("      4 |       6 |      Jytää |     3.44 "); 
    assertEquals("From: Kappale line: 135", "4|6|Jytää|3.44", kap.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString157 */
  @Test
  public void testToString157() {    // Kappale: 157
    Kappale kap = new Kappale(); 
    kap.parse("      4 |       6 |      Jytää |     3.44 "); 
    assertEquals("From: Kappale line: 160", "4|6|Jytää|3.44", kap.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna199 */
  @Test
  public void testAnna199() {    // Kappale: 199
    Kappale kap = new Kappale(); 
    kap.parse(" 4 | 6 | Jytää | 3.44 "); 
    assertEquals("From: Kappale line: 202", "4", kap.anna(0)); 
    assertEquals("From: Kappale line: 203", "6", kap.anna(1)); 
    assertEquals("From: Kappale line: 204", "Jytää", kap.anna(2)); 
    assertEquals("From: Kappale line: 205", "3.44", kap.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta252 */
  @Test
  public void testAseta252() {    // Kappale: 252
    Kappale kap = new Kappale(); 
    assertEquals("From: Kappale line: 254", "Sekunnit väärin", kap.aseta(3, "3.456")); 
    assertEquals("From: Kappale line: 255", null, kap.aseta(3, "3.34")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone293 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone293() throws CloneNotSupportedException {    // Kappale: 293
    Kappale kap = new Kappale(); 
    kap.parse(" 4 | 6 | Jytää | 3.44 "); 
    Kappale kopio = kap.clone(); 
    assertEquals("From: Kappale line: 298", kap.toString(), kopio.toString()); 
    kap.parse(" 1 | 2 | Rytää | 6.54 "); 
    assertEquals("From: Kappale line: 300", false, kopio.toString().equals(kap.toString())); 
  } // Generated by ComTest END
}