package albumirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.23 15:27:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi76 */
  @Test
  public void testRekisteroi76() {    // Kappale: 76
    Kappale laulu1 = new Kappale(); 
    assertEquals("From: Kappale line: 78", 0, laulu1.getTunnusNro()); 
    laulu1.rekisteroi(); 
    Kappale laulu2 = new Kappale(); 
    laulu2.rekisteroi(); 
    int n1 = laulu1.getTunnusNro(); 
    int n2 = laulu2.getTunnusNro(); 
    assertEquals("From: Kappale line: 84", n2-1, n1); 
  } // Generated by ComTest END
}