package albumirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.26 12:11:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // Rekisteri: 38
    Rekisteri rekisteri = new Rekisteri(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(); 
    levy1.rekisteroi(); levy2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 43", 0, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 44", 1, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy2); assertEquals("From: Rekisteri line: 45", 2, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 46", 3, rekisteri.getAlbumit()); 
    assertEquals("From: Rekisteri line: 47", levy1, rekisteri.annaAlbumi(0)); 
    assertEquals("From: Rekisteri line: 48", levy2, rekisteri.annaAlbumi(1)); 
    assertEquals("From: Rekisteri line: 49", levy1, rekisteri.annaAlbumi(2)); 
    try {
    assertEquals("From: Rekisteri line: 50", levy1, rekisteri.annaAlbumi(3)); 
    fail("Rekisteri: 50 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 51", 4, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 52", 5, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 53", 6, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 54", 7, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 55", 8, rekisteri.getAlbumit()); 
    try {
    rekisteri.lisaa(levy1); 
    fail("Rekisteri: 56 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}