package albumirekisteri.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import albumirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.30 13:44:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa55 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa55() throws SailoException {    // Rekisteri: 55
    Rekisteri rekisteri = new Rekisteri(); 
    Albumi levy1 = new Albumi(), levy2 = new Albumi(); 
    levy1.rekisteroi(); levy2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 60", 0, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 61", 1, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy2); assertEquals("From: Rekisteri line: 62", 2, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 63", 3, rekisteri.getAlbumit()); 
    assertEquals("From: Rekisteri line: 64", levy1, rekisteri.annaAlbumi(0)); 
    assertEquals("From: Rekisteri line: 65", levy2, rekisteri.annaAlbumi(1)); 
    assertEquals("From: Rekisteri line: 66", levy1, rekisteri.annaAlbumi(2)); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 67", 4, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 68", 5, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 69", 6, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 70", 7, rekisteri.getAlbumit()); 
    rekisteri.lisaa(levy1); assertEquals("From: Rekisteri line: 71", 8, rekisteri.getAlbumit()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKappaleet105 */
  @Test
  public void testAnnaKappaleet105() {    // Rekisteri: 105
    Kappaleet kappaleet = new Kappaleet(); 
    Kappale kap1 = new Kappale(); 
    kap1.vastaaMaailmanParasLaulu(1); 
    Kappale kap2 = new Kappale(); 
    kap2.vastaaMaailmanParasLaulu(2); 
    Kappale kap11 = new Kappale(); 
    kap11.vastaaMaailmanParasLaulu(1); 
    kappaleet.lisaa(kap1); 
    kappaleet.lisaa(kap2); 
    kappaleet.lisaa(kap11); 
    List<Kappale> loytyneet; 
    loytyneet = kappaleet.annaKappaleet(3); 
    assertEquals("From: Rekisteri line: 119", 0, loytyneet.size()); 
    loytyneet = kappaleet.annaKappaleet(1); 
    assertEquals("From: Rekisteri line: 121", 2, loytyneet.size()); 
  } // Generated by ComTest END
}